### ISSUE TITLE
Apartado de blog/noticias

### ISSUE THREAD

**Issue by migueabellan** [escornabot/website#2]
Estaría bien añadir un apartado para noticias sobre eventos, ferias, etc..

**Comment by rafacouto** [comment]
Tal vez podamos encontrar un plugin que coja las entradas del twitter @escornabot filtradas por tag, con la idea de mantener las publicaciones en twitter y que si se le pone el tag "#website" o similar al twit también salga en la web. Con que el plugin procese el twitter cada día sería suficiente.

**Comment by migueabellan** [comment]
Creado el apartado de noticias similar a la de la web. 

El plugin de entradas de twitter puede añadirse en algún sitio de la web mostrando las entradas .... cierro la issue y creo otra con eso.
