### ISSUE TITLE
Añadir Pestaña de Donde?

### ISSUE THREAD

**Issue by chetosvsgeez** [escornabot/website#3]
Seria útil una pestaña de los grupos en cada ciudad, y un Link al mapa de Lobotic de los escornabot por el mundo.

**Comment by rafacouto** [comment]
Lo pondría bajo menú "Comunidad". También enlace destacado en la portada al mapa (tal vez una imagen de muestra del mapa enlazando a él)

**Comment by chetosvsgeez** [comment]
lo de ponerla en una pestaña en la pagina principal , es para responder a todas las preguntas 
Que-Como-Cuando-Donde 
"Cuando" cuando surge escornabot y su filosofia, los padres del bicho

**Comment by migueabellan** [comment]
Cierro esta issue porque está reflejada en esta: https://github.com/escornabot/website/issues/8
